version: '3.3'

services:

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    env_file:
      - .env
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb_data:/data/db
    networks:
      - jsearch

volumes:
  mongodb_data:


networks:
  jsearch:
